name: Development deployment
'on':
  push:
    branches:
      - develop
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
      working-directory: web-app
    - name: Build
      run: npm run build
      working-directory: web-app
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Deploy
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GREVIEWS_DEV }}'
        channelId: live
        projectId: greviews-dev
    env:
        FIREBASE_CLI_PREVIEWS: hostingchannels
