name: Deploy to Development on merge
'on':
  push:
    branches:
      - develop
jobs:
  install_dependencies:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g @angular/cli & npm i
        working-directory: web-app
  build:
    if: false
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir ../public & ng build
        working-directory: web-app
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Deploying App"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GREVIEWS_DEV }}'
          channelId: live
          projectId: greviews-dev
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
